In [1]:
import pandas as pd
import numpy as np

In [2]:
# 定义相对路径
file_data_dictionary = 'data/data_dictionary.csv'
file_summerOly_athletes = 'data/summerOly_athletes.csv'
file_summerOly_hosts = 'data/summerOly_hosts.csv'
file_summerOly_medal_counts = 'data/summerOly_medal_counts.csv'
file_summerOly_programs = 'data/summerOly_programs.csv'

# 读取表格
df_data_dictionary = pd.read_csv(
    file_data_dictionary,
    encoding='utf-8',
    encoding_errors='ignore'  # 忽略解码错误
)

df_summerOly_athletes = pd.read_csv(
    file_summerOly_athletes,
    encoding='utf-8',
    encoding_errors='ignore'  # 忽略解码错误
)

df_summerOly_hosts = pd.read_csv(
    file_summerOly_hosts,
    encoding='utf-8',
    encoding_errors='ignore'  # 忽略解码错误
)

df_summerOly_medal_counts = pd.read_csv(
    file_summerOly_medal_counts,
    encoding='utf-8',
    encoding_errors='ignore'  # 忽略解码错误
)

df_summerOly_programs = pd.read_csv(
    file_summerOly_programs,
    encoding='utf-8',
    encoding_errors='ignore'  # 忽略解码错误
)

In [16]:
result1 = df_summerOly_athletes[['Name', 'Sex','NOC','Year','Sport','Event','Medal']].drop_duplicates()
result1.groupby('Name')
result1

,Name,Sex,NOC,Year,Sport,Event,Medal
0,A Dijiang,M,CHN,1992,Basketball,Basketball Men's Basketball,No medal
1,A Lamusi,M,CHN,2012,Judo,Judo Men's Extra-Lightweight,No medal
2,Gunnar Aaby,M,DEN,1920,Football,Football Men's Football,No medal
3,Edgar Aabye,M,DEN,1900,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,Cornelia (-strannood),F,NED,1932,Athletics,Athletics Women's 100 metres,No medal
...,...,...,...,...,...,...,...
252560,Sefora Ada,F,GEQ,2024,Athletics,Women's 100m,No medal
252561,Emanuela Liuzzi,F,ITA,2024,Wrestling,Women's Freestyle 50kg,No medal
252562,Isayah Boers,M,NED,2024,Athletics,4 x 400m Relay Mixed,Gold
252563,Kevin Staut,M,FRA,2024,Equestrian,Jumping Team,Bronze
252564,Charlie Carvell,M,GBR,2024,Athletics,Men's 4 x 400m Relay,Bronze

In [15]:
result1.to_csv('ProcessedData/Athletes.csv')